class FeatureItem {
  final String title;

  final String url;

  const FeatureItem(this.title, {this.url});
}

const List<FeatureItem> kFeatureItems = [
  const FeatureItem('24.ae'),
  const FeatureItem('About.com', url: 'https://web.archive.org/web/20010122014000/http://shareware.about.com/compute/shareware/library/ctools/bl_add_remove_plus.htm'),
  const FeatureItem('Actualidad Gadget'),
  const FeatureItem('AddictiveTips', url: 'https://www.addictivetips.com/windows-tips/lonecolor-quickly-set-any-solid-color-as-desktop-background/'),
  const FeatureItem('Ampercent'),
  const FeatureItem('Australian Financial Review'),
  const FeatureItem('Baidu Encyclopedia', url: 'https://baike.baidu.com/item/%E9%9A%8F%E6%9C%BA%E6%88%96%E6%8C%87%E5%AE%9A%E6%A1%8C%E9%9D%A2%E9%A2%9C%E8%89%B2LoneColor'),
  const FeatureItem('Baixaki', url: 'https://www.baixaki.com.br/download/lonecolor.htm'),
  const FeatureItem('BetaNews'),
  const FeatureItem('BIHON', url: 'https://www.bihon.ro/stirile-judetului-bihor/tabara-de-vara-pentru-tinerii-antreprenori-287358/'),
  const FeatureItem('BlogsDNA'),
  const FeatureItem('Boston Herald'),
  const FeatureItem('CHIP', url: 'https://archive.org/details/CHIP_Issue_2004-05'),
  const FeatureItem('Cinco Días'),
  const FeatureItem('CNET'),
  const FeatureItem('CNN', url: 'https://edition.cnn.com/2000/TECH/computing/03/14/top.free.idg/'),
  const FeatureItem('College Info Geek', url: 'https://web.archive.org/web/20160928091128/http://collegeinfogeek.com/5-time-management-tips/'),
  const FeatureItem('COMPUTER BILD'),
  const FeatureItem('Computer Idea', url: 'https://archive.org/details/computer-idea-074'),
  const FeatureItem('Computer Shopper'),
  const FeatureItem('Computertaal'),
  const FeatureItem('Computerworld', url: 'https://www.computerworld.com/article/2568164/kill-your-data.html'),
  const FeatureItem('connect'),
  const FeatureItem('Crişana', url: 'https://www.crisana.ro/stiri/cultura-5/evenimentul-11even-vorbitori-de-seama-la-oradea-38285.html'),
  const FeatureItem('Digi24'),
  const FeatureItem('Digital Trends', url: 'https://www.digitaltrends.com/computing/how-to-fix-a-dead-pixel/'),
  const FeatureItem('dotTech'),
  const FeatureItem('Download Squad'),
  const FeatureItem('Download3K'),
  const FeatureItem('EC-Council'),
  const FeatureItem('Entrepreneur', url: 'https://www.entrepreneur.com/article/25218'),
  const FeatureItem('EMAZING', url: 'https://web.archive.org/web/20010610235917/http://archives.emazing.com/archives/download/2000-01-19'),
  const FeatureItem('Evidence Technology Magazine'),
  // const FeatureItem('experto.de'),
  const FeatureItem('Federal University of Minas Gerais', url: 'https://repositorio.ufmg.br/handle/1843/BUOS-94LLRQ'),
  const FeatureItem('FileCluster'),
  const FeatureItem('FindMySoft'),
  const FeatureItem('Freeware.de'),
  const FeatureItem('Freewaregenius'),
  const FeatureItem('Freeweird'),
  const FeatureItem('Gekissimo'),
  const FeatureItem('gHacks Technology News'),
  const FeatureItem('GIGA'),
  const FeatureItem('Globedia', url: 'http://globedia.com/lonecolor-configura-color-solido-fondo-escritorio-rapidamente'),
  const FeatureItem('Government Computer News'),
  const FeatureItem('Guidami.info'),
  const FeatureItem('I Love Free Software'),
  const FeatureItem('IDG'),
  const FeatureItem('Infopackets'),
  const FeatureItem('InformIT'),
  const FeatureItem('iPlaza Magazine'),
  const FeatureItem('Kim Komando', url: 'https://www.komando.com/smartphones-gadgets/quickest-way-to-fix-dead-pixels-on-your-monitor/416926/'),
  const FeatureItem('Lifehacker', url: 'https://lifehacker.com/cinemadrape-creates-a-distraction-free-zone-for-any-app-5465228'),
  const FeatureItem('LO4D', url: 'https://cinemadrape.en.lo4d.com/windows'),
  const FeatureItem('MajorGeeks', url: 'https://www.majorgeeks.com/files/details/cinemadrape.html'),
  const FeatureItem('Omicrono'),
  const FeatureItem('PC & Tech Authority'),
  const FeatureItem('PC Advisor'),
  const FeatureItem('PC Magazine'),
  const FeatureItem('PC Open', url: 'https://archive.org/details/pc-open-2002-12/'),
  const FeatureItem('PC-WELT', url: 'https://www.pcwelt.de/tipps/Passwoerter-in-Chrome-sichtbar-machen-9020031.html'),
  const FeatureItem('PC World'),
  const FeatureItem('PCGuia', url: 'https://web.archive.org/web/20040620095607/http://www.xl.pt/pcg/0302/livro/a01-02-00.shtml'),
  const FeatureItem('PCnet'),
  const FeatureItem('PCPlus', url: 'https://archive.org/details/PC_Plus_Super_Disc_Issue_179_Side_B_August_2001'),
  const FeatureItem('PCSPACE', url: 'https://archive.org/details/pc_space_09-2001'),
  const FeatureItem('Revision3', url: 'http://web.archive.org/web/20150414054552/http://revision3.com/tzdaily/2010-07-01cinedrape/'),
  const FeatureItem('Revista Do CD-ROM', url: 'https://issuu.com/michelfranca/docs/revista_do_cdrom_050'),
  const FeatureItem('Rocky Bytes'),
  const FeatureItem('Sarasota PC Monitor', url: 'https://web.archive.org/web/20040616105551/http://spcug.org/reviews/hg0202.htm'),
  const FeatureItem('SC Magazine'),
  const FeatureItem('Simtel', url: 'https://web.archive.org/web/20040622024716/http://www.simtel.net/drff/drffpick31.php'),
  const FeatureItem('Smart Computing', url: 'https://en.wikipedia.org/wiki/SmartComputing'),
  const FeatureItem('SmartWorld'),
  const FeatureItem('SoftMania.sk'),
  const FeatureItem('Softoxi'),
  const FeatureItem('Softpedia', url: 'https://mobile.softpedia.com/android/LoneColor-Android-Review-1485.html'),
  const FeatureItem('Software Informer', url: 'https://lonecolor.informer.com/'),
  const FeatureItem('Superdownloads'),
  const FeatureItem('Svet kompjutera'),
  const FeatureItem('Taimienphi'),
  const FeatureItem('Tech Advisor'),
  const FeatureItem('Technology Personalized', url: 'https://techpp.com/2014/05/26/best-windows-tools-capsa-iseepass/'),
  const FeatureItem('TechRepublic'),
  // const FeatureItem('Techworld'),
  const FeatureItem('The Australian Financial Review', url: 'https://www.afr.com/politics/get-to-know-the-inside-information-20030916-jv186'),
  const FeatureItem('The Columbia Daily Tribune', url: 'https://web.archive.org/web/20040910225922/http://archive.showmenews.com/2002/Feb/20020204Busi002.asp'),
  const FeatureItem('The Guardian'),
  const FeatureItem('The New York Times'),
  const FeatureItem('The Tribune India', url: 'https://www.tribuneindia.com/2002/20020624/login/free.htm'),
  const FeatureItem('Times Computing', url: 'https://web.archive.org/web/20001205231200/http://timescomputing.com/19991013/psh3.html'),
  const FeatureItem('Total Tech'),
  const FeatureItem('TrishTech'),
  const FeatureItem('Uptodown'),
  const FeatureItem('Vector Magazine', url: 'https://www.vector.co.jp/magazine/softnews/140326/n1403261_reviewer.html'),
  const FeatureItem('Vnunet', url: 'https://web.archive.org/web/20020209141736/http://www.vnunet.com/Download/1115897'),
  const FeatureItem('Washington Post'),
  const FeatureItem('Web User Magazine', url: 'https://www.zinio.com/gb/webuser/april-22-2010-i115872#/'),
  const FeatureItem('Windows: The Official Magazine'),
  const FeatureItem('Xataka Android', url: 'https://www.xatakandroid.com/personalizacion/cinco-aplicaciones-para-poner-fondos-de-pantalla-negros-en-moviles-con-pantalla-amoled'),
  const FeatureItem('Yahoo Finance', url: 'https://finance.yahoo.com/news/notice-something-wrong-monitor-fix-131556471.html'),
  const FeatureItem('YourLifeUpdated', url: 'https://www.yourlifeupdated.net/guide/come-riparare-i-pixel-bruciati-su-qualsiasi-display/'),
  const FeatureItem('Ziarul Curentul', url: 'https://www.curentul.info/pagini-specializate/programele-de-securitate-rup-gura-targului/'),
  const FeatureItem('Ziarul de Iaşi', url: 'https://www.ziaruldeiasi.ro/economic/aviatia-militara-a-statelor-unite-este-clientul-unei-firme-de-soft-din-oradea~ni20vm'),
  const FeatureItem('Ziarul Financiar', url: 'https://www.zf.ro/zf-english/de-ce-sa-refuzi-un-salariu-de-peste-5-000-de-dolari-pe-luna-2863335'),
];
