const List<String> kContentFeatures = <String>[
  '24.ae',
  'Actualidad Gadget',
  'AddictiveTips',
  'Ampercent',
  'Australian Financial Review',
  'Baidu Encyclopedia',
  'Baixaki',
  'BetaNews',
  'BlogsDNA',
  'Boston Herald',
  'CHIP',
  'Cinco Días',
  'CNET',
  'CNN',
  'COMPUTER BILD',
  'Computertaal',
  'Computerworld',
  'Computer Shopper',
  'connect',
  'Digi24',
  'Digital Trends',
  'dotTech',
  'Download3K',
  'Download Squad',
  'EC-Council',
  'Evidence Technology Magazine',
  'experto.de',
  'FileCluster',
  'FindMySoft',
  'Freeware.de',
  'Freewaregenius',
  'Freeweird',
  'Gekissimo',
  'gHacks Technology News',
  'GIGA',
  'Globedia',
  'Government Computer News',
  'Guidami.info',
  'I Love Free Software',
  'IDG',
  'Infopackets',
  'InformIT',
  'iPlaza Magazine',
  'Lifehacker',
  'LO4D',
  'MajorGeeks',
  'Omicrono',
  'PC Advisor',
  'PC & Tech Authority',
  'PCnet',
  'PC Magazine',
  'PC Welt',
  'PC World',
  'Revision3',
  'Rocky Bytes',
  'SC Magazine',
  'Smart Computing',
  'SmartWorld',
  'SoftMania.sk',
  'Softoxi',
  'Softpedia',
  'Software Informer',
  'Superdownloads',
  'Svet kompjutera',
  'Taimienphi',
  'Tech Advisor',
  'TechPP',
  'TechRepublic',
  'Techworld',
  'The Guardian',
  'The New York Times',
  'Total Tech',
  'TrishTech',
  'Uptodown',
  'Vector',
  'Washington Post',
  'Web User',
  'Windows: The Official Magazine',
  'Xataka',
  'Yahoo Finance',
  'YourLifeUpdated',
];
