class FeatureItem {
  final String title;

  final String url;

  const FeatureItem(this.title, {this.url});
}

const List<FeatureItem> kFeatureItems = [
  const FeatureItem('24.ae'),
  const FeatureItem('Actualidad Gadget'),
  const FeatureItem('Ampercent'),
  const FeatureItem('BlogsDNA'),
  const FeatureItem('Boston Herald'),
  const FeatureItem('Cinco Días'),
  const FeatureItem('COMPUTER BILD'),
  const FeatureItem('Computer Shopper'),
  const FeatureItem('Computertaal'),
  const FeatureItem('connect'),
  const FeatureItem('dotTech'),
  const FeatureItem('Download3K'),
  const FeatureItem('EC-Council'),
  const FeatureItem('Evidence Technology Magazine'),
  // const FeatureItem('experto.de'),
  const FeatureItem('FileCluster'),
  const FeatureItem('FindMySoft'),
  const FeatureItem('Freeware.de'),
  const FeatureItem('Freewaregenius'),
  const FeatureItem('Freeweird'),
  const FeatureItem('Gekissimo'),
  const FeatureItem('gHacks Technology News'),
  const FeatureItem('GIGA'),
  const FeatureItem('Government Computer News'),
  const FeatureItem('Guidami.info'),
  const FeatureItem('I Love Free Software'),
  const FeatureItem('IDG'),
  const FeatureItem('Infopackets'),
  const FeatureItem('InformIT'),
  const FeatureItem('iPlaza Magazine'),
  const FeatureItem('PC & Tech Authority'),
  const FeatureItem('PC Advisor'),
  const FeatureItem('PC Magazine'),
  const FeatureItem('PC World'),
  const FeatureItem('PCnet'),
  const FeatureItem('Rocky Bytes'),
  const FeatureItem('SC Magazine'),
  const FeatureItem('SmartWorld'),
  const FeatureItem('SoftMania.sk'),
  const FeatureItem('Softoxi'),
  const FeatureItem('Superdownloads'),
  const FeatureItem('Svet kompjutera'),
  const FeatureItem('Taimienphi'),
  const FeatureItem('Tech Advisor'),
  const FeatureItem('TechRepublic'),
  // const FeatureItem('Techworld'),
  const FeatureItem('The Guardian'),
  const FeatureItem('The New York Times'),
  const FeatureItem('Total Tech'),
  const FeatureItem('TrishTech'),
  const FeatureItem('Uptodown'),
  const FeatureItem('Washington Post'),
  const FeatureItem('Windows: The Official Magazine'),
];
