class FeatureItem {
  final String title;

  final String url;

  const FeatureItem(this.title, {this.url});
}

const List<FeatureItem> kFeatureItems = [
  const FeatureItem('24.ae'),
  const FeatureItem('Actualidad Gadget'),
  const FeatureItem('AddictiveTips'),
  const FeatureItem('Ampercent'),
  const FeatureItem('Australian Financial Review'),
  const FeatureItem('Baidu Encyclopedia'),
  const FeatureItem('Baixaki'),
  const FeatureItem('BetaNews'),
  const FeatureItem('BlogsDNA'),
  const FeatureItem('Boston Herald'),
  const FeatureItem('CHIP'),
  const FeatureItem('Cinco Días'),
  const FeatureItem('CNET'),
  const FeatureItem('CNN', url: 'https://edition.cnn.com/2000/TECH/computing/03/14/top.free.idg/'),
  const FeatureItem('COMPUTER BILD'),
  const FeatureItem('Computertaal'),
  const FeatureItem('Computerworld'),
  const FeatureItem('Computer Shopper'),
  const FeatureItem('connect'),
  const FeatureItem('Digi24'),
  const FeatureItem('Digital Trends'),
  const FeatureItem('dotTech'),
  const FeatureItem('Download3K'),
  const FeatureItem('Download Squad'),
  const FeatureItem('EC-Council'),
  const FeatureItem("Entrepreneur", url: "https://www.entrepreneur.com/article/25218"),
  const FeatureItem('Evidence Technology Magazine'),
  const FeatureItem('experto.de'),
  const FeatureItem('FileCluster'),
  const FeatureItem('FindMySoft'),
  const FeatureItem('Freeware.de'),
  const FeatureItem('Freewaregenius'),
  const FeatureItem('Freeweird'),
  const FeatureItem('Gekissimo'),
  const FeatureItem('gHacks Technology News'),
  const FeatureItem('GIGA'),
  const FeatureItem('Globedia'),
  const FeatureItem('Government Computer News'),
  const FeatureItem('Guidami.info'),
  const FeatureItem('I Love Free Software'),
  const FeatureItem('IDG'),
  const FeatureItem('Infopackets'),
  const FeatureItem('InformIT'),
  const FeatureItem('iPlaza Magazine'),
  const FeatureItem('Lifehacker'),
  const FeatureItem('LO4D'),
  const FeatureItem('MajorGeeks'),
  const FeatureItem('Omicrono'),
  const FeatureItem('PC Advisor'),
  const FeatureItem('PC & Tech Authority'),
  const FeatureItem('PCnet'),
  const FeatureItem('PC Magazine'),
  const FeatureItem('PC Welt'),
  const FeatureItem('PC World'),
  const FeatureItem('Revision3'),
  const FeatureItem('Rocky Bytes'),
  const FeatureItem('SC Magazine'),
  const FeatureItem('Smart Computing'),
  const FeatureItem('SmartWorld'),
  const FeatureItem('SoftMania.sk'),
  const FeatureItem('Softoxi'),
  const FeatureItem('Softpedia'),
  const FeatureItem('Software Informer'),
  const FeatureItem('Superdownloads'),
  const FeatureItem('Svet kompjutera'),
  const FeatureItem('Taimienphi'),
  const FeatureItem('Tech Advisor'),
  const FeatureItem('TechPP'),
  const FeatureItem('TechRepublic'),
  const FeatureItem('Techworld'),
  const FeatureItem('The Australian Financial Review', url: 'https://www.afr.com/politics/get-to-know-the-inside-information-20030916-jv186'),
  const FeatureItem('The Guardian'),
  const FeatureItem('The New York Times'),
  const FeatureItem('The Tribune India', url: 'https://www.tribuneindia.com/2002/20020624/login/free.htm'),
  const FeatureItem('Total Tech'),
  const FeatureItem('TrishTech'),
  const FeatureItem('Uptodown'),
  const FeatureItem('Vector'),
  const FeatureItem('Washington Post'),
  const FeatureItem('Web User'),
  const FeatureItem('Windows: The Official Magazine'),
  const FeatureItem('Xataka'),
  const FeatureItem('Yahoo Finance'),
  const FeatureItem('YourLifeUpdated'),
];
